name: CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: gitlab-registry.cern.ch/atlas-physics-office/gitlab-integration/pogitlab

    steps:
    - uses: actions/checkout@v3

    - name: Configure Make
      run: make

