name: Latex Make

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: texlive/texlive

    steps:
    - uses: actions/checkout@v3

    - name: Compile
      run: xelatex *.tex
      
    - name: Archive artifacts
      uses: actions/upload-artifact@v3
      with:
        name: curriculum
        path: ./*pdf
        retention-days: 5

    - name: Download all workflow run artifacts
      uses: actions/download-artifact@v3

